In [2]:
import numpy as np

In [3]:
x_3d_list = [[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]]
x_3d = np.array(x_3d_list)

In [4]:
print(x_3d[0,:,:])

[[1 2 3]
 [4 5 6]]


In [5]:
print(f"The 0 element is {x_3d_list[0]}")
print(f"The 1 element is {x_3d_list[1]}")

The 0 element is [[1, 2, 3], [4, 5, 6]]
The 1 element is [[10, 20, 30], [40, 50, 60]]


In [6]:
print(f"The 0 element of the 1 element is {x_3d_list[1][0]}")
print(f"The 1 element of the 1 element is {x_3d_list[1][1]}")

The 0 element of the 1 element is [10, 20, 30]
The 1 element of the 1 element is [40, 50, 60]


In [7]:
print(f"The 2 element of the 1 element of the 1 element is {x_3d_list[1][1][2]}")

The 2 element of the 1 element of the 1 element is 60


In [8]:
print(x_3d[1,1,2])

60


In [9]:
x_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(x_2d[1])
print(x_2d[1,2])

[4 5 6]
6


if you look at the above indexing, innermost indexing is returning the 2nd row for inner-most value of 1. However, the outermost value of 2 is returning 6 which means 3rd column element in that row. therefore, it means that innermost index corresponds to rows and outermost index corresponds to columns. 

In [13]:
print(x_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [27]:
print(x_3d[:,1,1:3])

[[ 5  6]
 [50 60]]


In [28]:
print(x_3d_list)


[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]


In [29]:
print(x_3d_list*4)

[[[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]], [[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]], [[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]], [[1, 2, 3], [4, 5, 6]], [[10, 20, 30], [40, 50, 60]]]


So if an integer is multiplied by the list, the elements are duplicated that many times in the list.

What does it mean when the question says how does this differ?

In [37]:
i = 0.03
M = 100
C = 5

# Define array here
N = np.arange(1,11)
print(N)

# price bonds here
bond_list = []
for j in N:
    coupon = C*((1-(1+i)**(-j))/i)
    maturity = M*((1+i)**(-j))
    bond_list.append(coupon+maturity)

print(bond_list)

[ 1  2  3  4  5  6  7  8  9 10]
[101.94174757281554, 103.82693939108304, 105.65722270978937, 107.43419680562076, 109.15941437438907, 110.83438288775639, 112.4605659104431, 114.03938437907098, 115.57221784375821, 117.06040567355166]
